spring:
  application:
    name: server

  profiles:
    include: secret

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  cloud:
    aws:
      s3:
        bucket: my-fridge-415851145587-input
      region:
        static: ap-northeast-2
      stack:
        auto: false